CREATE DATABASE restaurant_db;
USE restaurant_db;
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(15),
    PASSWORD VARCHAR(60)
);

CREATE TABLE TABLES (
    TABLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAPACITY INT,
    STATUS VARCHAR(10)
);

CREATE TABLE RESERVATION (
    RESERVATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    TABLE_ID INT,
    CUSTOMER_ID INT,
    DATE_TIME DATETIME,
    FOREIGN KEY (TABLE_ID) REFERENCES TABLES(TABLE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE MENU_ITEMS (
    MENU_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    DISH_NAME VARCHAR(50),
    PRICE DECIMAL(10, 2)
);

CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    TABLE_ID INT,
    ORDER_DATE DATETIME,
    STATUS VARCHAR(15),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (TABLE_ID) REFERENCES TABLES(TABLE_ID)
);

CREATE TABLE ORDER_DETAILS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    MENU_ITEM_ID INT,
    QUANTITY INT,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    PAYMENT_DATE DATETIME,
    AMOUNT DECIMAL(10,2),
    PAYMENT_METHOD VARCHAR(15),
    TRANSACTION_ID VARCHAR(50),
    PAYMENT_STATUS VARCHAR(10),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

/* Prepopulate some tables and menu items for demo */
INSERT INTO TABLES (CAPACITY, STATUS) VALUES (2, 'available'), (4, 'available'), (6, 'available');
INSERT INTO MENU_ITEMS (DISH_NAME, PRICE) VALUES ('Paneer Tikka', 250.00), ('Butter Naan', 50.00), ('Chicken Biryani', 350.00);
